### ISSUE TITLE
`apollo-boost` dont't work with SSR?

### ISSUE THREAD

**Issue by michelleyschen** [michelleyschen/shopify-app#24]
https://github.com/apollographql/apollo-client/issues/3193#issuecomment-376160297

```
 app/foundation/App/tests/App.test.tsx
  ● Test suite failed to run


    fetch is not found globally and no fetcher passed, to fix pass a fetch for
    your environment like https://www.npmjs.com/package/unfetch.

    For example:
    import fetch from 'unfetch';
    import { createHttpLink } from 'apollo-link-http';

    const link = createHttpLink({ uri: '/graphql', fetch: fetch });

      at Object.checkFetcher (node_modules/apollo-link-http-common/lib/bundle.umd.js:78:19)
      at createHttpLink (node_modules/apollo-link-http/lib/bundle.umd.js:32:30)
      at new HttpLink (node_modules/apollo-link-http/lib/bundle.umd.js:203:38)
      at new DefaultClient (node_modules/apollo-boost/lib/index.js:93:24)
      at Object.<anonymous> (app/foundation/App/App.tsx:9:16)
      at Object.<anonymous> (app/foundation/App/tests/App.test.tsx:15:287)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
          at Generator.next (<anonymous>)
```

**Comment by michelleyschen** [comment]
can no longer reproduce
